"""remove edition

Revision ID: 51df9353da0a
Revises: 5b5bf4a59430
Create Date: 2023-11-13 15:29:03.755304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51df9353da0a'
down_revision = '5b5bf4a59430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('edition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
